//! 把冻结的 antd token 显式映射到 gpui-component `ThemeColor` 的全部槽位。
//!
//! 用结构体字面量而不是在默认主题上改几项：gpui-component 升级时增删槽位会直接编译失败，
//! 逼着在这里逐项决定，不会悄悄漏出 shadcn 的黑白默认色。

use gpui::{Hsla, transparent_black};
use gpui_component::ThemeColor;

use super::antd::AntdColors;

/// 按 antd token 生成 gpui-component 的颜色表。
pub fn theme_color(a: &AntdColors) -> ThemeColor {
    let c = |color: super::antd::TokenColor| -> Hsla { color.to_hsla() };
    let transparent = transparent_black();

    ThemeColor {
        // 菜单项、下拉选项悬停：antd `controlItemBgHover`。
        accent: c(a.control_item_bg_hover),
        accent_foreground: c(a.color_text),
        accordion: c(a.color_bg_container),
        background: c(a.color_bg_container),
        // 浮层、对话框描边：antd 浮层本身无描边，取最浅的 `colorBorderSecondary`。
        border: c(a.color_border_secondary),
        // 默认按钮：底色不变、悬停叠一层填充色（gpui-component 只能改底色，不能像 antd 那样改描边和字色）。
        button: c(a.color_bg_container),
        button_active: c(a.color_fill_secondary),
        button_foreground: c(a.color_text),
        button_hover: c(a.color_fill_tertiary),
        button_danger: c(a.color_error),
        button_danger_active: c(a.color_error_active),
        button_danger_foreground: c(a.color_text_light_solid),
        button_danger_hover: c(a.color_error_hover),
        button_info: c(a.color_info),
        button_info_active: c(a.color_info_active),
        button_info_foreground: c(a.color_text_light_solid),
        button_info_hover: c(a.color_info_hover),
        button_primary: c(a.color_primary),
        button_primary_active: c(a.color_primary_active),
        button_primary_foreground: c(a.color_text_light_solid),
        button_primary_hover: c(a.color_primary_hover),
        button_secondary: c(a.color_fill_tertiary),
        button_secondary_active: c(a.color_fill),
        button_secondary_foreground: c(a.color_text),
        button_secondary_hover: c(a.color_fill_secondary),
        button_success: c(a.color_success),
        button_success_active: c(a.color_success_active),
        button_success_foreground: c(a.color_text_light_solid),
        button_success_hover: c(a.color_success_hover),
        button_warning: c(a.color_warning),
        button_warning_active: c(a.color_warning_active),
        button_warning_foreground: c(a.color_text_light_solid),
        button_warning_hover: c(a.color_warning_hover),
        group_box: c(a.color_fill_quaternary),
        group_box_foreground: c(a.color_text),
        caret: c(a.color_text),
        chart_1: c(a.blue_6),
        chart_2: c(a.cyan_6),
        chart_3: c(a.green_6),
        chart_4: c(a.orange_6),
        chart_5: c(a.purple_6),
        chart_bullish: c(a.green_6),
        chart_bearish: c(a.red_6),
        chart_grid: c(a.color_split),
        danger: c(a.color_error),
        danger_active: c(a.color_error_active),
        danger_foreground: c(a.color_text_light_solid),
        danger_hover: c(a.color_error_hover),
        description_list_label: c(a.color_fill_quaternary),
        description_list_label_foreground: c(a.color_text_secondary),
        drag_border: c(a.color_primary),
        drop_target: c(a.color_primary_bg),
        foreground: c(a.color_text),
        info: c(a.color_info),
        info_active: c(a.color_info_active),
        info_foreground: c(a.color_text_light_solid),
        info_hover: c(a.color_info_hover),
        // 输入框、选择器、默认按钮的描边：antd `colorBorder`。
        input: c(a.color_border),
        link: c(a.color_link),
        link_active: c(a.color_link_active),
        link_hover: c(a.color_link_hover),
        list: c(a.color_bg_container),
        list_active: c(a.control_item_bg_active),
        list_active_border: c(a.color_primary),
        list_even: c(a.color_fill_quaternary),
        list_head: c(a.color_fill_quaternary),
        list_hover: c(a.control_item_bg_hover),
        // 骨架、Kbd 底色。
        muted: c(a.color_fill_secondary),
        // gpui-component 拿它画占位符、禁用字和次要说明，取居中的 `colorTextTertiary`。
        muted_foreground: c(a.color_text_tertiary),
        popover: c(a.color_bg_elevated),
        popover_foreground: c(a.color_text),
        primary: c(a.color_primary),
        primary_active: c(a.color_primary_active),
        primary_foreground: c(a.color_text_light_solid),
        primary_hover: c(a.color_primary_hover),
        progress_bar: c(a.color_primary),
        // 聚焦边框与聚焦环（环为它的半透明版）：antd 聚焦边框是 `colorPrimary`。
        ring: c(a.color_primary),
        scrollbar: transparent,
        // 1.x OverlayScrollbars 的滑块：quaternary，悬停 tertiary。
        scrollbar_thumb: c(a.color_text_quaternary),
        scrollbar_thumb_hover: c(a.color_text_tertiary),
        secondary: c(a.color_fill_tertiary),
        secondary_active: c(a.color_fill),
        secondary_foreground: c(a.color_text),
        secondary_hover: c(a.color_fill_secondary),
        selection: c(a.control_item_bg_active_hover),
        sidebar: c(a.color_bg_layout),
        sidebar_accent: c(a.control_item_bg_hover),
        sidebar_accent_foreground: c(a.color_text),
        sidebar_border: c(a.color_border_secondary),
        sidebar_foreground: c(a.color_text),
        sidebar_primary: c(a.color_primary),
        sidebar_primary_foreground: c(a.color_text_light_solid),
        skeleton: c(a.color_fill_secondary),
        // antd Slider：轨道 `colorPrimaryBorder`，手柄 `colorBgElevated`。
        slider_bar: c(a.color_primary_border),
        slider_thumb: c(a.color_bg_elevated),
        success: c(a.color_success),
        success_foreground: c(a.color_text_light_solid),
        success_hover: c(a.color_success_hover),
        success_active: c(a.color_success_active),
        // antd Switch：关闭时轨道 `colorTextQuaternary`，手柄 `colorWhite`。
        switch: c(a.color_text_quaternary),
        switch_thumb: c(a.color_white),
        // antd Segmented：轨道 `colorBgLayout`，选中项 `colorBgElevated`，未选中字色 `colorTextSecondary`。
        tab: transparent,
        tab_active: c(a.color_bg_elevated),
        tab_active_foreground: c(a.color_text),
        tab_bar: c(a.color_bg_container),
        tab_bar_segmented: c(a.color_bg_layout),
        tab_foreground: c(a.color_text_secondary),
        table: c(a.color_bg_container),
        table_active: c(a.control_item_bg_active),
        table_active_border: c(a.color_primary),
        table_even: c(a.color_fill_quaternary),
        table_head: c(a.color_fill_quaternary),
        table_head_foreground: c(a.color_text),
        table_foot: c(a.color_fill_quaternary),
        table_foot_foreground: c(a.color_text),
        table_hover: c(a.color_fill_quaternary),
        table_row_border: c(a.color_border_secondary),
        title_bar: c(a.color_bg_container),
        title_bar_border: c(a.color_border_secondary),
        status_bar: c(a.color_bg_container),
        status_bar_border: c(a.color_border_secondary),
        warning: c(a.color_warning),
        warning_active: c(a.color_warning_active),
        warning_hover: c(a.color_warning_hover),
        warning_foreground: c(a.color_text_light_solid),
        // 弹窗遮罩：antd `colorBgMask`。
        overlay: c(a.color_bg_mask),
        window_border: c(a.color_border),
        red: c(a.red_6),
        red_light: c(a.red_1),
        green: c(a.green_6),
        green_light: c(a.green_1),
        blue: c(a.blue_6),
        blue_light: c(a.blue_1),
        yellow: c(a.yellow_6),
        yellow_light: c(a.yellow_1),
        magenta: c(a.magenta_6),
        magenta_light: c(a.magenta_1),
        cyan: c(a.cyan_6),
        cyan_light: c(a.cyan_1),
    }
}
