//! 把角色化色板和语义 token 显式映射到 gpui-component `ThemeColor` 的全部槽位。
//!
//! 用结构体字面量而不是在默认主题上改几项：gpui-component 升级时增删槽位会直接编译失败，
//! 逼着在这里逐项决定，不会悄悄漏出 shadcn 的黑白默认色。

use gpui::{Hsla, transparent_black};
use gpui_component::ThemeColor;

use super::{palette::Palette, semantic::SemanticTokens};

/// 按 antd token 生成 gpui-component 的颜色表。
pub fn theme_color(p: &Palette, s: &SemanticTokens) -> ThemeColor {
    let c = |color: Hsla| -> Hsla { color };
    let transparent = transparent_black();

    ThemeColor {
        // 菜单项、下拉选项悬停：antd `controlItemBgHover`。
        accent: c(p.items.hover.hsla()),
        accent_foreground: c(s.text.primary),
        accordion: c(s.surface.panel),
        background: c(s.surface.panel),
        // 浮层、对话框描边：antd 浮层本身无描边，取最浅的 `colorBorderSecondary`。
        border: c(s.border.subtle),
        // 默认按钮：底色不变、悬停叠一层填充色（gpui-component 只能改底色，不能像 antd 那样改描边和字色）。
        button: c(s.surface.panel),
        button_active: c(s.fill.default),
        button_foreground: c(s.text.primary),
        button_hover: c(s.fill.subtle),
        button_danger: c(s.status.danger.solid),
        button_danger_active: c(s.status.danger.active),
        button_danger_foreground: c(s.text.on_accent),
        button_danger_hover: c(s.status.danger.hover),
        button_info: c(s.status.info.solid),
        button_info_active: c(s.status.info.active),
        button_info_foreground: c(s.text.on_accent),
        button_info_hover: c(s.status.info.hover),
        button_primary: c(s.accent.solid),
        button_primary_active: c(s.accent.active),
        button_primary_foreground: c(s.text.on_accent),
        button_primary_hover: c(s.accent.hover),
        button_secondary: c(s.fill.subtle),
        button_secondary_active: c(s.fill.strong),
        button_secondary_foreground: c(s.text.primary),
        button_secondary_hover: c(s.fill.default),
        button_success: c(s.status.success.solid),
        button_success_active: c(s.status.success.active),
        button_success_foreground: c(s.text.on_accent),
        button_success_hover: c(s.status.success.hover),
        button_warning: c(s.status.warning.solid),
        button_warning_active: c(s.status.warning.active),
        button_warning_foreground: c(s.text.on_accent),
        button_warning_hover: c(s.status.warning.hover),
        group_box: c(s.fill.faint),
        group_box_foreground: c(s.text.primary),
        caret: c(s.text.primary),
        chart_1: c(p.extras.blue_6.hsla()),
        chart_2: c(p.extras.cyan_6.hsla()),
        chart_3: c(p.extras.green_6.hsla()),
        chart_4: c(p.extras.orange_6.hsla()),
        chart_5: c(p.extras.purple_6.hsla()),
        chart_bullish: c(p.extras.green_6.hsla()),
        chart_bearish: c(p.extras.red_6.hsla()),
        chart_grid: c(s.border.divider),
        danger: c(s.status.danger.solid),
        danger_active: c(s.status.danger.active),
        danger_foreground: c(s.text.on_accent),
        danger_hover: c(s.status.danger.hover),
        description_list_label: c(s.fill.faint),
        description_list_label_foreground: c(s.text.secondary),
        drag_border: c(s.accent.solid),
        drop_target: c(s.accent.subtle),
        foreground: c(s.text.primary),
        info: c(s.status.info.solid),
        info_active: c(s.status.info.active),
        info_foreground: c(s.text.on_accent),
        info_hover: c(s.status.info.hover),
        // 输入框、选择器、默认按钮的描边：antd `colorBorder`。
        input: c(s.border.default),
        link: c(s.accent.text),
        link_active: c(s.accent.text_active),
        link_hover: c(s.accent.text_hover),
        list: c(s.surface.panel),
        list_active: c(p.items.selected.hsla()),
        list_active_border: c(s.accent.solid),
        list_even: c(s.fill.faint),
        list_head: c(s.fill.faint),
        list_hover: c(p.items.hover.hsla()),
        // 骨架、Kbd 底色。
        muted: c(s.fill.default),
        // gpui-component 拿它画占位符、禁用字和次要说明，取居中的 `colorTextTertiary`。
        muted_foreground: c(s.text.muted),
        popover: c(s.surface.raised),
        popover_foreground: c(s.text.primary),
        primary: c(s.accent.solid),
        primary_active: c(s.accent.active),
        primary_foreground: c(s.text.on_accent),
        primary_hover: c(s.accent.hover),
        progress_bar: c(s.accent.solid),
        // 聚焦与展开时的边框：比常态描边深一档的中性色，不用主色（光晕在 `apply` 里关掉）。
        ring: c(s.text.faint),
        scrollbar: transparent,
        // 1.x OverlayScrollbars 的滑块：quaternary，悬停 tertiary。
        scrollbar_thumb: c(s.text.faint),
        scrollbar_thumb_hover: c(s.text.muted),
        secondary: c(s.fill.subtle),
        secondary_active: c(s.fill.strong),
        secondary_foreground: c(s.text.primary),
        secondary_hover: c(s.fill.default),
        selection: c(p.items.selected_hover.hsla()),
        sidebar: c(s.surface.window),
        sidebar_accent: c(p.items.hover.hsla()),
        sidebar_accent_foreground: c(s.text.primary),
        sidebar_border: c(s.border.subtle),
        sidebar_foreground: c(s.text.primary),
        sidebar_primary: c(s.accent.solid),
        sidebar_primary_foreground: c(s.text.on_accent),
        skeleton: c(s.fill.default),
        // antd Slider：轨道 `colorPrimaryBorder`，手柄 `colorBgElevated`。
        slider_bar: c(s.accent.border),
        slider_thumb: c(s.surface.raised),
        success: c(s.status.success.solid),
        success_foreground: c(s.text.on_accent),
        success_hover: c(s.status.success.hover),
        success_active: c(s.status.success.active),
        // antd Switch：关闭时轨道 `colorTextQuaternary`，手柄 `colorWhite`。
        switch: c(s.text.faint),
        switch_thumb: c(s.white),
        // antd Segmented：轨道 `colorBgLayout`，选中项 `colorBgElevated`，未选中字色 `colorTextSecondary`。
        tab: transparent,
        tab_active: c(s.surface.raised),
        tab_active_foreground: c(s.text.primary),
        tab_bar: c(s.surface.panel),
        tab_bar_segmented: c(s.surface.window),
        tab_foreground: c(s.text.secondary),
        table: c(s.surface.panel),
        table_active: c(p.items.selected.hsla()),
        table_active_border: c(s.accent.solid),
        table_even: c(s.fill.faint),
        table_head: c(s.fill.faint),
        table_head_foreground: c(s.text.primary),
        table_foot: c(s.fill.faint),
        table_foot_foreground: c(s.text.primary),
        table_hover: c(s.fill.faint),
        table_row_border: c(s.border.subtle),
        title_bar: c(s.surface.panel),
        title_bar_border: c(s.border.subtle),
        status_bar: c(s.surface.panel),
        status_bar_border: c(s.border.subtle),
        warning: c(s.status.warning.solid),
        warning_active: c(s.status.warning.active),
        warning_hover: c(s.status.warning.hover),
        warning_foreground: c(s.text.on_accent),
        // 弹窗遮罩：antd `colorBgMask`。
        overlay: c(s.surface.mask),
        window_border: c(s.border.default),
        red: c(p.extras.red_6.hsla()),
        red_light: c(p.extras.red_1.hsla()),
        green: c(p.extras.green_6.hsla()),
        green_light: c(p.extras.green_1.hsla()),
        blue: c(p.extras.blue_6.hsla()),
        blue_light: c(p.extras.blue_1.hsla()),
        yellow: c(p.extras.yellow_6.hsla()),
        yellow_light: c(p.extras.yellow_1.hsla()),
        magenta: c(p.extras.magenta_6.hsla()),
        magenta_light: c(p.extras.magenta_1.hsla()),
        cyan: c(p.extras.cyan_6.hsla()),
        cyan_light: c(p.extras.cyan_1.hsla()),
    }
}
